CXXFLAGS = -g -std=c++17 -Wall -Wextra -Werror
CXX      = g++

game: shaderprog.o renderer.o handler.o game.o
	${CXX} $(CXXFLAGS)  $^ -o $@ -lglut

game.o: src/main.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@ -lglut

handler.o: src/lib/handler.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@ -lglut

renderer.o: src/lib/renderer.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@ -lglut

shaderprog.o: src/lib/shaderprog.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@ -lglut

clean:
	rm -f *.o lex format calc
