CXXFLAGS = -g -std=c++17 -Wall -Wextra -Werror
CXX      = g++

game: shaderprog.o renderer.o handler.o game.o
	${CXX} $(CXXFLAGS)  $^ -o $@

game.o: src/main.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@

handler.o: src/lib/handler.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@

renderer.o: src/lib/renderer.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@

shaderprog.o: src/lib/shaderprog.cpp
	${CXX} $(CXXFLAGS)  $^ -c -o $@

clean:
	rm -f *.o lex format calc
